---
kind: Service
apiVersion: v1
metadata:
  name: petservice
spec:
  selector:
    app: docker-pets
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 5000
      # Port accessible outside cluster
      nodePort: 30000
  type: LoadBalancer



---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-pets
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: docker-pets
    spec:
      containers:
        - name: docker-pets
          image: docker-pets:v0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000